language: scala
scala:
  - 2.13.6
sudo: required
services:
  - docker
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag calculators:1.0 $DOCKER_USERNAME/calculators:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/calculators:$TRAVIS_BUILD_NUMBER
  - docker tag calculators:1.0 $DOCKER_USERNAME/calculators:latest
  - docker push $DOCKER_USERNAME/calculators:latest